spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/platform?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver